redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/ubuntu/eSPLIT-demo"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/js/script.js"
to = "https://plausible.io/js/script.js"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/v1/*"
to = "https://plausible.io/api/v1/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]